data61/clkhash

clkhash/benchmark.py
clkhash/cli.py
clkhash/clk.py
requirements.txt
setup.py
tests/test_benchmark.py
tests/test_cli.py

Adds a simple progress bar for the command line utility.
I think the `generate_clk_from_csv` function should expose a better api for progress for other callers though - maybe a progress queue, or callback function?

Add a progress bar for cli based hashing

---

Jenkinsfile
README.md
clkhash/benchmark.py
clkhash/bloomfilter.py
clkhash/clk.py
clkhash/identifier_types.py
clkhash/key_derivation.py
clkhash/randomnames.py
clkhash/schema.py
clkhash/tokenizer.py
requirements.txt
setup.py

Python 2 and 3 compatible type annotations for the mypy static type checker.
I've been testing with:
```
pip install mypy
mypy clkhash --ignore-missing-imports --strict-optional --no-implicit-optional --disallow-untyped-calls
```

Typing Annotations

---

clkhash/bloomfilter.py
clkhash/identifier_types.py
tests/test_e2e_hashing.py

weight now adjusts the number of hash functions being used in the Bloom filter generation.
fixes #18

recognise the `weight` of an identifier in filter generation

---

clkhash/bloomfilter.py
docs/conf.py
tests/test_bloomfilter.py

I added a modified version of the double hash encoding scheme which does not have the singularity weakness of the original one. See accompanying issue #33.
closes #33

Feature always double encoding

---

CHANGELOG.md
setup.py

This release candidate can be tested from PyPi:
```
$ pip install clkhash==0.10.0rc1
$ clkutil benchmark
generating CLKs: 100%|█████████████████████████████████████████████████████████████████| 10.0K/10.0K [00:01<00:00, 8.22Kclk/s, mean=521, std=34.4]
10000 hashes in 1.267577 seconds. 7.89 KH/s
```

Changelog for 0.10 release

---

clkhash/randomnames.py
tests/test_names.py

The `generate_subsets()` method in `NameList` did not protect against unreasonable parameters. Specifically, if it was asked to generate `n` names in the constructor, then `sz + (1 - overlap)*sz` must be less than `n` for `generate_subsets()` to be able to work. A `ValueError` is now raised if this condition is not met.
This PR also includes a considerable simplification of the code for generating the subsets, as well as a few improvements/clarifications to the documentation.
This PR is a precursor to a solution to entity-service/issues/99.

Fix generate_subsets method

---

CHANGELOG.md
README.md
clkhash/bloomfilter.py
docs/conf.py
docs/index.rst
docs/references.rst
setup.py

Bump version and update changelog for `0.10.1`. 
Most likely the last release before #69 is merged in.
_Update_: Have just added another few commits to change the docs. Have pushed a release candidate to PyPy: https://pypi.org/project/clkhash/0.10.1rc2/
Can test it out with:
```
pip install clkhash==0.10.1rc2
```

0.10.1 release

---

clkhash/data/randomnames-schema.json

we do not want to hash INDEX and k was too small. With k=30 we set about 430 bits.

the default shema was not quite right

---

clkhash/bloomfilter.py
clkhash/clk.py
clkhash/field_formats.py
clkhash/key_derivation.py
clkhash/randomnames.py
clkhash/schema.py
clkhash/tokenizer.py
clkhash/validate_data.py
tests/test_bloomfilter.py
tests/test_cli.py
tests/test_clk.py
tests/test_key_derivation.py
tests/test_names.py
tests/test_stats.py

In a bunch of places we’ve been unnecessarily allocating memory by making lists. This pull request does the following two things to avoid that:
- Imports `range`, `map`, `zip` from `future` when appropriate. These are the versions that are iterators.
- Recognises that `tuple` and `set` will happily accept an iterator, so no need to make a list first.

Use iterators to avoid unnecessary memory allocation

---

clkhash/backports.py
clkhash/bloomfilter.py
clkhash/data/randomnames-schema.json
clkhash/field_formats.py
clkhash/master-schemas/v1.json
clkhash/schema.py
clkhash/validate_data.py
docs/_static/example_schema.json
docs/schema.rst
tests/test_clk.py
tests/test_field_formats.py
tests/test_validate_data.py

The date spec is now a bit more sensible. 
The problems I solved are:
- only one allowed date type
- we hashed unnecessary characters like '-'
The master schema changed such that it allows defining dates with a format string just like in `strftime()`. 
A FieldSpec now has an additional `format_value` function which will return a given field value nicely formatted for hashing. FieldSpec need to overwrite `_format_regular_value` to implement custom behavior. Default is return what you get.
In the case of dates, we will always return a string in YYYYMMDD format.
This same mechanism will also be used for more sensible Integer support.

Feature support better date type

---

clkhash/field_formats.py
clkhash/master-schemas/v1.json
docs/schema.rst
tests/test_field_formats.py

two things:
- we now support negative integers. (You can always look at the positive side of things...)
- we are more forgiving on the input integer strings. The problem was that there are several valid integer strings for on integer. E.g.: `' 1'`, `'+1'`, `'1 '` are all valid and parse-able strings for the integer `1`. We now first parse the integer string to an integer, then pass it on for hashing without white-spaces and `+`.

support for negative integers

---

clkhash/randomnames.py

Stop creating attributes outside of __init__

---

tests/test_backports.py
tests/test_clk.py
tests/test_tokenizer.py
tests/test_validate_data.py

Fixes #101 by removing unused imports from the tests. I was unable to find any unused imports in the clkhash library itself.

Remove unnecessary imports

---

clkhash/backports.py
clkhash/cli.py
clkhash/rest_client.py
tests/test_cli.py
tests/test_rest_client.py

Extra feature for the rest_client - wait for run completion.
One function yields status updates, one just waits until the very end (or until a timeout expires).
~I could change the generator to only give updates that have "changed" - not just every second. But interested in your thoughts.~  Now implemented.

Create two helper functions to wait for a run to complete

---

README.md
dependencies.yml

By adding this config file and adding the GitHub application for https://app.dependencies.io/projects/github/n1analytics/clkhash we should get notified when our library dependencies have updates.
This is to address https://github.com/n1analytics/clkhash/issues/97

Add support for dependenies.io

---

.travis.yml
CHANGELOG.md
clkhash/rest_client.py
setup.py
tox.ini

Opps I introduced a bug which raises a runtime error in the most recent pythons. The fact this isn't picked up in our tests is captured in #177
Source:
> Finally, the proposal also clears up the confusion about how to terminate a generator: the proper way is return, not raise StopIteration.
https://www.python.org/dev/peps/pep-0479/

Bugfix in restclient - generators should terminate with return

---

.travis.yml

Turns out the `TEST_ENTITY_SERVICE` env var is required to call the external service. Now enabled for Python 3.7
Closes #177

Travis to run rest_client tests on python3.7

---

.travis.yml
clkhash/__init__.py
clkhash/backports.py
clkhash/bloomfilter.py
clkhash/cli.py
clkhash/clk.py
clkhash/describe.py
clkhash/serialization.py
setup.py
tests/test_bloomfilter.py
tests/test_describe.py
tests/test_schema.py
tests/test_serialization.py

Questions in # TODO: comments.
Works: python{,3} -m clkhash.cli describe fake-clk.json
Works: python3 -m unittest tests/test_bloomfilter.py
but with python (2):
...
File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
module = __import__('.'.join(parts_copy))
ImportError: Import by filename is not supported.
Type checker not yet run.
All improvements/comments welcome.

Cli describe

---

clkhash/cli.py
tests/test_cli.py

This is a change to the CLI. The rest client module already supported multi-party linkage.

Support multi-party linkage in the Entity Service

---

clkhash/field_formats.py
tests/test_field_formats.py
tests/test_schema.py

I wrote some tests to check if the handling of 'Ignored' features is correct.
More specifically, I want good failures.
Currently one test fails, because field_formats raises an `InvalidSchemaError`, caused by `KeyError`.
I argue that this should be an `InvalidEntryError`. (see descriptions of InvalidSchemaError and InvalidEntryError). 
More generally, I want to be allowed:
```
{
"identifier": "good",
"ignored": true
}
```
```
{
"identifier": "good_with_format",
"ignored": true,
"format": {
"type": "date", "format": "%Y-%m-%d"},
"hashing": {"ngram": 1, "strategy": {"k": 20}}
}
```
```
{
"identifier": "good_with_format",
"ignored": false,
"format": {
"type": "date", "format": "%Y-%m-%d"},
"hashing": {"ngram": 1, "strategy": {"k": 20}}
}
```
but not
```
{
"identifier": "good",
"ignored": …
```

Testing ignored

---

clkhash/tokenizer.py
docs/tutorial_api.ipynb
docs/tutorial_cli.ipynb
setup.py
tests/test_tokenizer.py

There is a bug in the tokenizer.
If a feature is encoded as bi-grams and a value happens to be empty, then the tokenizer would return a token of two white-spaces. However, the correct behavior would be to return nothing.
This is especially bad for the *variable-k* encoding scheme:
A missing value, as it will be tokenized into a "  " token, would be encoded with *numBits* bits. Thus all entities with missing values for that feature will have all those bits in common and in turn an inflated similarity score. This screws up the matching pretty badly!

Fix tokenizer

---

.azurePipeline/wholeBuild.yml
CHANGELOG.md
requirements.txt
setup.py

This change means users no longer require a C compiler to install clkhash.
While waiting to see whether the upstream `bitarray` library will distribute binary wheels (in https://github.com/ilanschnell/bitarray/pull/76) this PR switches to my fork which publishes binary wheels for each platform from a CI. See also issue #153 
https://pypi.org/project/bitarray-hardbyte/
🤡

Switch to using a fork of bitarray that distributes binary wheels.

---

clkhash/data/randomnames-schema.json
tests/test_e2e_hashing.py
tests/testdata/randomnames-schema-v1.json

The schema of the inbuilt data generator was still version 1.
This PR fixes this.
closes  #310

Update randomnames schema

---

.azurePipeline/wholeBuild.yml

The build https://dev.azure.com/data61/Anonlink/_build/results?buildId=755&view=results shows a surprising behavior:
in the stage `build and test`, on the first attempt, the job "Test with pytest" fails, but its publishing step still ran, because of which re-running the failed jobs fails as the PublishArtifact step cannot overwrite artifacts.
I thought we could do as in the entity-service, i.e. creating a new artifact including the attempt number, but it works in the entity-service because the artifact is not consumed by another job, so its name become irrelevant. Here we need to know its name to be used in the `package` stage.
If we were creating a new artifact for each attemot, we would need to provide the new name to the package stage. To do this, my only thought would be to use …

Add a condition before running the Publish task.

---

clkhash/comparators.py
tests/test_comparators.py

The exact comparison and the numeric comparison didn't handle missing values properly.
missing values are delivered as an empty string to the tokenizer, the expected output would be an empty tuple.
This PR implements this functionality and tests for correctness.
closes #322

tokenizer of some comparison functions cannot handle missing values properly

---

tests/test_cli.py

same changes as in anonlink-client, 
- the timeout for the entity service interaction is now set to 60 sec, up from 20.
- the multiparty upload test now uses the proper wait function from the rest client.

more generous timeout and multiparty upload tests waits properly

---

.azurePipeline/wholeBuild.yml
azurePipeline.yml
codecov.yml

The bash uploader from codecov supports Azure without needing to configure secret tokens. This should resolve the issue seen in #340 where an external PR didn't pass CI.

Use codecov.io's bash uploader

---

clkhash/schemas/v3.json
docs/schema.rst
tests/test_schema.py
tests/testdata/ignorant-schema-v3.json

fixes #341
the schema validator couldn't decide which spec to apply if `"ignored": true` was added to a full feature config. More detail in #341

Fix schema v3

---

CHANGELOG.md
clkhash/cli.py
clkhash/rest_client.py
docs/cli.rst
docs/index.rst
docs/rest_client.rst
setup.py

As anonlink-client now implements the rest client and command line tool this functionality can be removed from clkhash.

Add deprecation notice for rest_client and cli

---

docs/doc-requirements.txt

we don't need typing any more since it is part of python3.
Also, the inclusion of the typing lib makes the readthedoc build break.

remove typing from doc-requirements.txt

---

clkhash/schemas/v3.json
tests/test_schema.py

the way the strategy was defined in the schema, one could specify
```"strategy": {"bitsPerToken": "illegalValue"}```
and the validation would not complain.
This PR fixes the definition of strategy in the schema.

Fix strategy definition

---

docs/schema.rst

one parameter was missing and another one was misnamed.

fix entry for numeric comparison

---

tests/test_benchmark.py

We have a test that runs the benchmark and requires a certain speed.
PyPy struggled to jump over that hurdle, due to the JIT compiler.
In order to get a better picture of the true performance of PyPy, I added a blind run of the benchmark, such that the JIT compiler can optimize during that, and then we execute the benchmark again with those optimizations in place.

add blind run for pypy

---

clkhash/__init__.py
docs/development.rst

Use importlib to access project version

Remove implicit dependency on setuptools

---

.github/workflows/build_publish.yml
.github/workflows/typechecking.yml
.github/workflows/unittests.yml
README.md
docs/devops.rst
docs/schema.rst
docs/tutorials.rst

I've renamed in GitHub, this PR just updates the docs.
Users that already have the project checked out may have to run:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Rename main branch
