- README.md
- clkhash/identifier_types.py
- docs/conf.py
- docs/doc-requirements.txt
- requirements.txt
- setup.py
http://clkhash.readthedocs.io/en/feature-readthedocs/
> Small updates to enable building on readthedocs

- CHANGELOG.md
- setup.py
- Changelog.
- Bump version number.
> Version 0.9.0

- .travis.yml
- Jenkinsfile
- README.md
- clkhash/clk.py
- requirements.txt
- setup.cfg
- setup.py
- tox.ini
For better open source collaboration we should have the CI builds be carried out by something public. E.g. Travis.
Closes #31
> Feature build with Travis-CI

- docs/_static/example_schema.json
- docs/_static/schema.json
- docs/index.rst
- docs/schema.rst
- requirements.txt
- tests/test_json_schema.py
I moved the schema from entity service to here and created some docs describing the schema.
closes #47
> schema migration and documentation

- clkhash/bloomfilter.py
> wrong type signature in stream_bloom_filters

- clkhash/clk.py
- clkhash/stats.py
- tests/test_stats.py
reports mean and standard deviation of the produced clks in the progress bar.
> Feature clk stats

- .appveyor.yml
- .travis.yml
- README.md
- clkhash/benchmark.py
- clkhash/bloomfilter.py
- clkhash/cli.py
- clkhash/clk.py
- clkhash/stats.py
- requirements.txt
- setup.py
- tests/__init__.py
- tests/test_benchmark.py
- tests/test_cli.py
- tests/test_schema.py
- tests/testdata/weighted-schema.json
Rebases and squashes changes from PR https://github.com/n1analytics/clkhash/pull/63 to better support Windows.
Primarily the changes are:
* concurrent hashing on windows and Python2
* cross platform temporary files for testing purposes.
* testing of CLI on windows
> Improved windows support

- README.md
Resolves #73 by explaining how to set up environment properly.
> Explain how to set up environment to run tests.

- .appveyor.yml
> Disable storing artifacts on app veyor

- CHANGELOG.md
- setup.py
Some changes to CHANGELOG.md. Changed version in setup.py.
> 0.11.0 release

- clkhash/__main__.py
> Add a __main__ script so `python -m clkhash` will launch the cli

- docs/schema.rst
- docs/tutorial.ipynb
- made it work with new schema
- developed a bit of a story around it
Still contains bits and pieces which are not ideal.
First round of comments is intended to work out what we want to change before release.
> Feature update tutorial

- .travis.yml
- docs/schema.rst
fixed link to master schema, removed the draft status
> fixed docs for schema

- clkhash/clk.py
- clkhash/field_formats.py
- clkhash/validate_data.py
Master is not passing Travis because of a Mypy update. This fixes that (hopefully).
> Fix Mypy issues in master

- clkhash/randomnames.py
- tests/test_names.py
Let `NameList.generate_subsets` generate more than 2 subsets. Implemented with optional parameter so not a breaking change.
> Multiparty testing with randomnames.

- clkhash/schema.py
Make `GlobalHashingProperties.__init__` accept arguments instead of a `**kwargs` dictionary. This means that we will error if required things are missing. It also lets us have defaults and Mypy types.
Implements #137.
> Minor API changes to schema

- .gitignore
- clkhash/benchmark.py
- clkhash/bloomfilter.py
- clkhash/field_formats.py
- clkhash/randomnames.py
- clkhash/schema.py
- clkhash/tokenizer.py
- clkhash/validate_data.py
Changes from Brendon after running an internal code review.
> Code formatting changes following internal code review

- docs/tutorial_api.ipynb
- docs/tutorial_cli.ipynb
it was missing the missing value definitions in the schemas.
> Fix tutorial

- clkhash/bloomfilter.py
- clkhash/clk.py
- clkhash/randomnames.py
- clkhash/schema.py
Bunch of minor issues with docstrings
> Bring docstrings are up to date

- clkhash/clk.py
- clkhash/rest_client.py
- requirements.txt
- setup.py
- tests/__init__.py
- tests/test_cli.py
- tests/test_rest_client.py
I felt guilty about not fully testing the rest_client abstraction in #159 
Also this testing seems to have exposed a bug in the entity service :-)
> Feature test rest client

- CHANGELOG.md
- requirements.txt
- setup.py
Strings together the open PRS #164 #165 #166 and #167
> Update deps 0.11.2

- codecov.yml
Adding a configuration to codecov as detailed [here](https://docs.codecov.io/docs/codecov-yaml)
Ignore coverage changes of <2%
> Add a codecov configuration file

- .travis.yml
- CHANGELOG.md
- setup.py
Pretty straightforward release
> Release 0.12.0

- README.md
- setup.py
> Add classifiers to setup and clearly state supported python versions

- clkhash/bloomfilter.py
- tests/test_bloomfilter.py
Remove class NgramEncodings(Enum) as per #205
> Redundant partial

- clkhash/bloomfilter.py
- clkhash/field_formats.py
- tests/test_bloomfilter.py
> use array of k's to fix bug #210

- CHANGELOG.md
- setup.py
- tests/test_clk.py
might as well do a release to show off our new windows binary packaging
> Prepare release 0 12 1

- docs/tutorial_api.ipynb
was broken.
Hero me fixed it.
fixes #236
> adjusted to new API, updated results

- CHANGELOG.md
- Jenkinsfile
- README.md
- clkhash/bloomfilter.py
- clkhash/schemas/v1.json
- clkhash/schemas/v2.json
- docs/index.rst
- docs/schema.rst
- docs/tutorial_api.ipynb
- setup.py
- tests/test_bloomfilter.py
(Replaces external fork PR https://github.com/data61/clkhash/pull/241)
> Replaced n1analytics with data61 for github links

- README.md
- docs/doc-requirements.txt
- requirements.txt
From https://requires.io/github/data61/clkhash/requirements/?branch=master to https://requires.io/github/data61/clkhash/requirements/?branch=update-requirements-2019-05
> Update all pinned requirements

- .appveyor.yml
- Jenkinsfile
- clkhash/cli.py
- docs/tutorial_cli.ipynb
- requirements.txt
- setup.py
- tests/test_cli.py
- tests/test_rest_client.py
Added project and run deletion commands to the command line. 
App Veyor deployment now handles existing uploads (to prepare for switching to Azure DevOps)
Updates to latest requirements. 
Note the latest version of `requests` didn't work for Python 3.4, as we don't officially support 3.4 anymore I removed them from jenkins and appveyor.
I tweaked the rest_client tests to not hash the CLK data for every single test.
> Deletion from command line

- README.md
just adding some bling to boost our cred.
> azure pipeline badge

- clkhash/schemas/v3.json
- docs/schema.rst
the schema docs weren't fully describing the current schema. Now it is all shiny.
fixes #253
> Fix schema docs

- clkhash/rest_client.py
- tests/test_cli.py
- tests/test_rest_client.py
* rest client update to accept 204 status on run deletion
* Remove duplicate test code
* Remove a hard coded wait flaky test
> Update rest client and tests

- clkhash/cli.py
- clkhash/schema.py
- docs/cli.rst
- tests/__init__.py
- tests/test_cli.py
- tests/test_schema.py
- tests/testdata/bad-schema-v3.json
I added a new command for the cli to convert a schema file to the latest version.
closes #206
> Feature cli schema converter

- clkhash/cli.py
- clkhash/schemas/v1.json
- tests/test_field_formats.py
- tests/test_key_derivation.py
We have compiled quite a list of warnings when running the tests.
This PR addresses all the issues raised.
> Reduce warnings in tests

- clkhash/cli.py
- docs/tutorial_api.ipynb
- docs/tutorial_cli.ipynb
The entity service changed the supported result types. 'mapping' is a thing of the past now.
This PR adjusts the tutorials and the cli to this new reality. 
also closes #301 as I changed the way we compute recall and precision
> Remove mapping type

- CHANGELOG.md
- README.md
- setup.py
also contains a sneaky readme fix.
> Release 0.15.0

- requirements.txt
- setup.py
See https://github.com/advisories/GHSA-7fcj-pq9j-wh2r
> Update PyInstaller version to 3.6

- docs/doc-requirements.txt
- requirements.txt
> bumping requirements to latest versions

- docs/devops.rst
updated the devops section to the new reality
> we don't do python2 any more.

- CHANGELOG.md
- setup.py
this is going to be the next pre-release for the new clkhash.
> new beta version

- .azurePipeline/wholeBuild.yml
- docs/doc-requirements.txt
- pytest.ini
- requirements.txt
> test notebooks on windows also

- .azurePipeline/wholeBuild.yml
- README.md
- azurePipeline.yml
- codecov.yml
- docs/doc-requirements.txt
support for 3.5 ended in September. 
In the meantime, they released 3.9. We better test that then...
> remove testing for python 3.5

- docs/doc-requirements.txt
dependabot is lacking behind. I'll give him a little boost.
> bump dependencies

- clkhash/benchmark.py
- clkhash/bloomfilter.py
- clkhash/clk.py
- clkhash/comparators.py
- clkhash/describe.py
- clkhash/field_formats.py
- clkhash/key_derivation.py
- clkhash/randomnames.py
- clkhash/schema.py
- clkhash/stats.py
- clkhash/validate_data.py
- docs/conf.py
I ran the [pyupgrade](https://github.com/asottile/pyupgrade) tool to update some old code. It would be tedious to do this manually.
To reproduce:
```
pip install pyupgrade
python -m pyupgrade --py37-plus $(find clkhash -name "*.py")
```
> Run pyupgrade --py37-plus
